service: timer-app-frontend

# frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 300
  region: eu-west-2
  # stage: ${opt:stage}
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - "*/*"

plugins:
  - serverless-esbuild

functions:
  TimerAppFrontend:
    name: timer-app-frontend-${self:provider.stage}
    handler: server.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

package:
  patterns:
    - ".next"
    - "node_modules"
    - "public"
    - "_next"
    - "next.config.js"
    - "next-i18next.config.js"
    - "package.json"

custom:
  esbuild:
    bundle: true
    minify: true
    exclude: "*"
    external:
      - "next"