version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-deploy-development:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: "Build app"

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build-deploy-development