version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Build and test'
          command: |
            export TEST=true
            yarn build
  deploy-development:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Deploy to development'
          command: |
            yarn sst secrets set --stage development SERVICE_API_URL $SERVICE_API_URL_DEVELOPMENT      
            yarn sst secrets set --stage development CLIENT_SECRET $CLIENT_SECRET_DEVELOPMENT      
            yarn deploy --stage development
  deploy-production:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Deploy to production'
          command: |
            yarn sst secrets set --stage production SERVICE_API_URL $SERVICE_API_URL_PRODUCTION 
            yarn sst secrets set --stage development CLIENT_SECRET $CLIENT_SECRET_PRODUCTION         
            yarn deploy --stage production
workflows:
  development-pipeline:
    jobs:
      - build-and-test
      - deploy-development:
          requires: 
            - build-and-test
          filters:
            branches:
              only: main
  production-pipeline:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: release
      - deploy-production:
          requires: 
            - build-and-test
          filters:
            branches:
              only: release
