version: 2.1

orbs:
  node: circleci/node@5.0.2
  win: circleci/windows@5.0

executors:
  pw-jammy-development:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.2-jammy

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Build and test'
          command: |
            export TEST=true
            yarn build_test

  e2e-tests:
    executor: win/default
    steps:
      - checkout
      - run:
          command: |
            nvm install 21
            nvm use 21
      - run:
          command: npm install --global yarn
      - run:
          name: Install Playwright
          command: |
            yarn
            yarn playwright install 
      - run:
          name: Run Playwright Tests
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            yarn test-ci
      - store_artifacts:
          path: ./playwright-report
          destination: playwright-report

  deploy-development:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Deploy to development'
          command: |
            yarn sst secrets set --stage development SERVICE_API_URL $SERVICE_API_URL_DEVELOPMENT      
            yarn sst secrets set --stage development CLIENT_SECRET $CLIENT_SECRET_DEVELOPMENT      
            AUTH_DOMAIN=$AUTH_DOMAIN_DEVELOPMENT CLIENT_ID=$CLIENT_ID_DEVELOPMENT BASE_URL=$BASE_URL_DEVELOPMENT AUDIENCE=$AUDIENCE_DEVELOPMENT REDIRECT_URI=$REDIRECT_URI_DEVELOPMENT yarn deploy --stage development
  deploy-production:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Deploy to production'
          command: |
            yarn sst secrets set --stage production SERVICE_API_URL $SERVICE_API_URL_PRODUCTION 
            yarn sst secrets set --stage production CLIENT_SECRET $CLIENT_SECRET_PRODUCTION         
            AUTH_DOMAIN=$AUTH_DOMAIN_PRODUCTION CLIENT_ID=$CLIENT_ID_PRODUCTION BASE_URL=$BASE_URL_PRODUCTION AUDIENCE=$AUDIENCE_PRODUCTION REDIRECT_URI=$REDIRECT_URI_PRODUCTION yarn deploy --stage production
workflows:
  cicd-pipeline:
    jobs:
      - build-and-test
      - e2e-tests
      - deploy-development:
          requires:
            - build-and-test
            - e2e-tests
          filters:
            branches:
              only: main
      - deploy-production:
          requires:
            - build-and-test
          filters:
            branches:
              only: release
