version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-deploy-development:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Build and deploy"
          command: |

            sudo npm i -g serverless@"<3"
            BUILD_FOLDER=.dist

            yarn build
            rm -rf $BUILD_FOLDER
            mv .next/standalone/ $BUILD_FOLDER/
            cp -r .next/static $BUILD_FOLDER/.next
            rm $BUILD_FOLDER/server.js
            cp -r next.config.js $BUILD_FOLDER/
            cp serverless.yml $BUILD_FOLDER/
            cp server.ts $BUILD_FOLDER/
            cp -r public $BUILD_FOLDER/
            cd $BUILD_FOLDER
            sls deploy --stage development


# yarn build && yarn --production=true && sudo npm i -g serverless@"<3" && sls deploy --stage development


workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build-deploy-development