version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test-and-deploy-development:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Build and deploy'
          command: |
            export NEXT_PUBLIC_SERVICE_API_KEY=$NEXT_PUBLIC_SERVICE_API_KEY_DEVELOPMENT
            export NEXT_PUBLIC_SERVICE_API_URL=$NEXT_PUBLIC_SERVICE_API_URL_DEVELOPMENT
            yarn build
            yarn deploy --stage development
  test-and-deploy-production:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Build and deploy'
          command: |
            export NEXT_PUBLIC_SERVICE_API_KEY=$NEXT_PUBLIC_SERVICE_API_KEY_PRODUCTION
            export NEXT_PUBLIC_SERVICE_API_URL=$NEXT_PUBLIC_SERVICE_API_URL_PRODUCTION
            yarn build
            yarn deploy --stage production

workflows:
  test-and-deploy-development:
    jobs:
      - test-and-deploy-development:
        filters:
          branches:
            only: main
  test-and-deploy-production:
    jobs:
      - test-and-deploy-production:
        filters:
          branches:
            only: release
