version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test-and-deploy-development:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Build and deploy'
          command: |
            npm install --global sst@^2.40.0
            npx sst secrets set SERVICE_API_KEY $SERVICE_API_KEY_DEVELOPMENT
            npx sst secrets set SERVICE_API_URL $SERVICE_API_URL_DEVELOPMENT      
            npx sst deploy --stage development
  test-and-deploy-production:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Build and deploy'
          command: |
            npm install --global sst@^2.40.0
            npx sst secrets set SERVICE_API_KEY $SERVICE_API_KEY_PRODUCTION
            npx sst secrets set SERVICE_API_URL $SERVICE_API_URL_PRODUCTION      
            npx sst deploy --stage production
workflows:
  development-pipeline:
    jobs:
      - test-and-deploy-development
          # filters:
          #   branches:
          #     only: main
  production-pipeline:
    jobs:
      - test-and-deploy-production:
          filters:
            branches:
              only: release
